### ISSUE TITLE
Opba false-positive

### ISSUE THREAD

**Issue by Ran392** [RogueDrifter/Anti_cheat_pack#16] opened 2019-01-16 15:39 UTC
**Describe the bug**
Sometimes, when a player spawns, Opba is called. I have noticed this on laggy clients most of all, and wondered if the movement from the death, to new spawn position, is causing it.

**To Reproduce**
Haven't been able to replicate.

**Expected behavior**
I expected the anti-cheat to have not been triggered.

**Screenshots**
N/A

**Samp details (please complete the following information):**
 - Version: 0.3.7 R2
 - Using filterscripts? Yes
 - Using sampctl? No

**Additional context**
N/A

**Comment by RogueDrifter** [comment] 2019-01-19 01:41
Hi, sorry for the late response mate, please do mention which breaktype it was.
```pawn
OnPlayerBreakAir(playerid, breaktype)
```
Types:
```breaktype 1: airbreak on foot.
breaktype 2: airbreak as driver.
breaktype 3: airbreak as passenger.
breaktype 4: teleport on foot.
breaktype 5: teleport as driver.
breaktype 6: teleport as passenger.```

**Comment by u9h5r** [comment] 2019-01-20 15:50
Hi Rogue,

I'm happy to say that your fixes have resolved the issue, after intensive testing, it's no longer happening! :)

I will still answer your questions, though:

 I'm not sure which breaktype it was, as I have some modifications which simply alert in-game admins, but do not specify the exact type of cheat (i.e. TP or AB on-foot or passenger).

1) I was (and still am) using FLaggers, included before OPBA
2) It was (and still is) included only in the main gamemode file (no where else).

As the issue is resolved, feel free to close this out.

Many thanks!

**Comment by RogueDrifter** [comment] 2019-01-20 23:37
Alrighty great thanks for reporting it, feel free to contact me or open another issue if you run into anything else

**Closed by RogueDrifter** 2019-01-20 23:37 UTC
Labels: In progress, bug
